### ISSUE TITLE
Documentation as to activate the rule

### ISSUE THREAD

**Issue by prebours** [SebastienGllmt/eslint-plugin-no-floating-promise#5]
In the `README`, it is not clear how the rules are activated by default:

I do not think that there is a rule called `rule-name`.

```
{
    "rules": {
        "no-floating-promise/rule-name": 2
    }
}
```

Should it be instead?
```
'no-floating-promise/no-floating-promise': ['error'],
```

**Comment by SebastienGllmt** [comment]
Ah yes, this comes from the default template when creating a new ESLint rule. I just fixed it in 1753304b24a0928cf0c1e92f867e61d65601772b
